number = int(input("Enter a positive integer."))
if number < 0:
    print("Not a positive integer.")
if number >= 0:
    print(number * 1)
    print(number * 2)
    print(number * 3)
    print(number * 4)
    print(number * 5)
    print(number * 6)
    print(number * 7)
    print(number * 8)
    print(number * 9)
    print(number * 10)
    print(number * 11)
    print(number * 12)